version: '3.8'

services:
  itp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - .:/app
    environment:
      - GO_ENV=development
    command: ["./itp"]
